# Generated by Django 3.1 on 2020-09-06 06:59

import camera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('entry_time', models.TimeField(default='12:34:56.000000')),
                ('exit_time', models.TimeField(default='13:34:56.000000')),
                ('customer_flow', models.ImageField(upload_to=camera.models.path_and_rename)),
                ('number_of_family_member', models.IntegerField()),
                ('client_gender', models.CharField(max_length=200)),
                ('client_age', models.IntegerField()),
                ('client_purchase_amount', models.FloatField()),
                ('client_previous_visit_time', models.DateTimeField()),
                ('client_visits_this_month', models.IntegerField()),
            ],
        ),
    ]
