# Generated by Django 3.1 on 2020-08-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_storemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemanager',
            name='store',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='camera.store'),
        ),
    ]
