# Generated by Django 3.1 on 2020-09-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_testuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='testuser_media',
            field=models.FileField(upload_to='home/harsh/django-dataviv/embedding'),
        ),
    ]
