# Generated by Django 3.1 on 2020-08-20 13:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('product_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('total_camera', models.IntegerField()),
                ('outer_camera_channel_no', models.CharField(max_length=200)),
                ('billing_camera_channel_no', models.CharField(max_length=200)),
                ('camera_sequence', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='camera.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='camera.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_in', models.IntegerField()),
                ('total_out', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailylogs', to='camera.organization')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailylogs', to='camera.store')),
            ],
        ),
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='camera.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='camera.organization')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='camera.store')),
            ],
        ),
    ]
