# Generated by Django 3.1 on 2020-09-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_previous_visit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
