# Generated by Django 3.1 on 2020-09-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20200906_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvgMaleCount', models.IntegerField()),
                ('AvgFemaleCount', models.IntegerField()),
                ('Ageunder18', models.IntegerField()),
                ('Age18to24', models.IntegerField()),
                ('Age25to34', models.IntegerField()),
                ('Age35to44', models.IntegerField()),
                ('Age45to54', models.IntegerField()),
                ('Age55to64', models.IntegerField()),
                ('Age65above', models.IntegerField()),
                ('Totalin', models.IntegerField()),
                ('Totalout', models.IntegerField()),
                ('AvgMissedcustomer', models.IntegerField()),
                ('AvgPurchasedvisit', models.IntegerField()),
                ('Avglinelength', models.IntegerField()),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analyticentrys', to='camera.store')),
            ],
        ),
    ]
