# Generated by Django 3.1 on 2020-09-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20200910_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='testuser_media',
            field=models.FileField(upload_to='./home/harsh/django-dataviv/embedding'),
        ),
    ]
