# Generated by Django 3.1 on 2020-08-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_analytic_dailylog_employee_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='product_image',
            new_name='employee_media',
        ),
    ]
