# Generated by Django 3.1 on 2020-08-30 17:58

import camera.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_storemanager_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_heat_map', models.ImageField(upload_to=camera.models.path_and_rename)),
                ('store_hot_zone', models.ImageField(upload_to=camera.models.path_and_rename)),
                ('gender', models.ImageField(upload_to=camera.models.path_and_rename)),
                ('duration_of_visit', models.ImageField(upload_to=camera.models.path_and_rename)),
                ('no_of_purchasing_visit', models.IntegerField()),
                ('no_of_missed_customers', models.IntegerField()),
                ('days_with_most_walkings', models.ImageField(upload_to=camera.models.path_and_rename)),
                ('average_employee_count', models.ImageField(upload_to=camera.models.path_and_rename)),
                ('average_line_length', models.ImageField(upload_to=camera.models.path_and_rename)),
                ('time_analysis', models.ImageField(upload_to=camera.models.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='TotalDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_walkings', models.IntegerField()),
                ('clients', models.CharField(max_length=200)),
                ('customer_flow', models.ImageField(upload_to=camera.models.path_and_rename)),
                ('number_of_family_member', models.IntegerField()),
                ('client_gender', models.CharField(max_length=200)),
                ('client_age', models.IntegerField()),
                ('client_purchase_amount', models.FloatField()),
                ('client_previous_visit_time', models.DateTimeField()),
                ('client_visits_this_month', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='analytic',
            name='store_heat_map',
            field=models.FileField(default=None, upload_to=camera.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='analytic',
            name='store_hot_zone',
            field=models.FileField(default=None, upload_to=camera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='analytics', to='camera.employee'),
        ),
    ]
