# Generated by Django 3.1 on 2020-08-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_auto_20200820_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_media',
            field=models.FileField(upload_to='Face_data'),
        ),
    ]
