# Generated by Django 3.1 on 2020-09-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_analyticentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
