# Generated by Django 3.1 on 2020-08-21 09:19

import camera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_auto_20200821_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_media',
            field=models.FileField(upload_to=camera.models.path_and_rename),
        ),
    ]
