# Generated by Django 3.1 on 2020-09-10 10:05

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_auto_20200910_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='camera.user')),
                ('name', models.CharField(max_length=200)),
                ('testuser_media', models.FileField(upload_to='storage_path')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('camera.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
