# Generated by Django 3.1 on 2020-09-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_passwordreset', '0003_allow_blank_and_null_fields'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('camera', '0006_testuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('testuser_media', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='TestUser',
        ),
    ]
