# Generated by Django 3.1 on 2020-09-14 08:05

import camera.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_auto_20200913_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_media', models.FileField(upload_to=camera.models.path_and_rename)),
            ],
        ),
        migrations.DeleteModel(
            name='TestUserb',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_media',
        ),
        migrations.AddField(
            model_name='employeemedia',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employeemedias', to='camera.employee'),
        ),
    ]
