# Generated by Django 3.1 on 2020-09-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_employee_employee_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_media',
            field=models.FileField(upload_to='Face_data'),
        ),
    ]
