# Generated by Django 3.1 on 2020-10-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0018_attendencemedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvgPurchasedvisit', models.PositiveIntegerField()),
                ('Avglinelength', models.PositiveIntegerField()),
                ('Date_Time', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis2s', to='camera.store')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvgMaleCount', models.PositiveIntegerField()),
                ('AvgFemaleCount', models.PositiveIntegerField()),
                ('AgeChild', models.PositiveIntegerField()),
                ('AgeTeenge', models.PositiveIntegerField()),
                ('AgeAdult', models.PositiveIntegerField()),
                ('AgeOld', models.PositiveIntegerField()),
                ('Totalin', models.PositiveIntegerField()),
                ('Totalout', models.PositiveIntegerField()),
                ('CustomerWalkin', models.PositiveIntegerField()),
                ('Date_Time', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis1s', to='camera.store')),
            ],
        ),
    ]
