# Generated by Django 3.1 on 2020-10-01 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0019_analysis1_analysis2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('classtype', models.CharField(default=None, max_length=1)),
                ('updatedclasstype', models.CharField(choices=[('E', 'Employee'), ('C', 'Customer'), ('O', 'Other')], default=None, max_length=1)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modelanalysiss', to='camera.store')),
            ],
        ),
    ]
