# Generated by Django 3.1 on 2020-10-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0021_auto_20201001_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis2',
            old_name='AvgPurchasedvisit',
            new_name='avg_linelength',
        ),
        migrations.RenameField(
            model_name='analysis2',
            old_name='Avglinelength',
            new_name='avg_purchased_visit',
        ),
        migrations.RenameField(
            model_name='analysis2',
            old_name='Date_Time',
            new_name='timestamp',
        ),
    ]
