# Generated by Django 3.1 on 2020-10-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0022_auto_20201001_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis1',
            old_name='AgeAdult',
            new_name='age_adult',
        ),
        migrations.RenameField(
            model_name='analysis1',
            old_name='AgeChild',
            new_name='age_child',
        ),
        migrations.RenameField(
            model_name='analysis1',
            old_name='AgeOld',
            new_name='age_old',
        ),
        migrations.RenameField(
            model_name='analysis1',
            old_name='AgeTeenge',
            new_name='age_teenge',
        ),
        migrations.RenameField(
            model_name='analysis1',
            old_name='AvgFemaleCount',
            new_name='avg_female_count',
        ),
        migrations.RenameField(
            model_name='analysis1',
            old_name='AvgMaleCount',
            new_name='avg_male_count',
        ),
        migrations.RenameField(
            model_name='analysis1',
            old_name='CustomerWalkin',
            new_name='customer_walkin',
        ),
        migrations.RenameField(
            model_name='analysis1',
            old_name='Date_Time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='analysis1',
            old_name='Totalin',
            new_name='total_in',
        ),
        migrations.RenameField(
            model_name='analysis1',
            old_name='Totalout',
            new_name='total_out',
        ),
    ]
