# Generated by Django 3.1 on 2020-10-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0023_auto_20201001_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelanalysis',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
