# Generated by Django 3.1 on 2020-10-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0025_auto_20201004_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
