# Generated by Django 3.1 on 2020-10-22 05:47

import camera.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0026_auto_20201004_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=camera.models.path_and_rename3)),
                ('store', models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='camera.store')),
            ],
        ),
    ]
