# Generated by Django 3.1 on 2020-10-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0027_storeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeimage',
            old_name='image',
            new_name='store_image',
        ),
    ]
